products = [
    {
        '_id': 1,
        'name': 'Cewnik do odsysania górnych dróg oddechowych',
        'image': '/images/cewnik.jpg',
        'description': 'Cewnik do odsysania górnych dróg oddechowych. Długość 40 cm. Służy do udrażniania oraz toalety górnych dróg oddechowych u pacjentów, u których istnieje potrzeba odessania wydzieliny zalegającej w górnych drogach oddechowych. Wyrób sterylny. Opakowanie 50 sztuk.',
        'price': 29.50, 
        'countInStock': 4,
        'rating': 4,
        'reviewsNum': 15, 
    },
    {
        '_id': 2,
        'name': 'Maska chirurgiczna',
        'image': '/images/maska.jpg',
        'description': 'Maski chirurgiczne trjówarstwowe medyczne niebieskie z włókniny z gumkami. Posiada certyfikat CE. Opakowanie 50 sztuk.',
        'price': 8.89, 
        'countInStock': 4,
        'rating': 4.5,
        'reviewsNum': 55, 
    },
    {
        '_id': 3,
        'name': 'Rękawice nitrylowe rozmiar M',
        'image': '/images/rekawice.jpg',
        'description': 'Jednorazowe rękawice medyczne nitrylowe diagnostyczno-zabiegowe. Rozmiar M. Bezpudrowe, niejałowe. Opakowanie 100 sztuk.',
        'price': 19.50, 
        'countInStock': 4,
        'rating': 4,
        'reviewsNum': 70, 
    },
    {
        '_id': 4,
        'name': 'Rękawice nitrylowe rozmiar S',
        'image': '/images/rekawice.jpg',
        'description': 'Jednorazowe rękawice medyczne nitrylowe diagnostyczno-zabiegowe. Rozmiar S. Bezpudrowe, niejałowe. Opakowanie 100 sztuk.',
        'price': 19.50, 
        'countInStock': 4,
        'rating': 5,
        'reviewsNum': 47, 
    },
    {
        '_id': 5,
        'name': 'Strzykawki 5ml',
        'image': '/images/strzykawka.jpg',
        'description': 'Strzykawki sterylne, jednorazowego użytku. Opakowanie 100 sztuk.',
        'price': 25, 
        'countInStock': 4,
        'rating': 4.5,
        'reviewsNum': 52, 
    },
    {
        '_id': 6,
        'name': 'Pojemnik na odpady medyczne',
        'image': '/images/odpady.jpg',
        'description': 'Pojemnik na odpady medyczne o pojemności 0,7 litra. Wykonany z tworzywa sztucznego - polipropylenu.',
        'price': 5, 
        'countInStock': 4,
        'rating': 5,
        'reviewsNum': 18, 
    },
    {
        '_id': 7,
        'name': 'Prześcierala papierowe 50cm',
        'image': '/images/podkladka.jpg',
        'description': 'Prześcieradła papierowe o wymiarach 50x50 cm w rolce. Przeznaczone do gabinetów lekarskich, zabiegowych, kosmetycznych itp.',
        'price': 24.99, 
        'countInStock': 4,
        'rating': 4,
        'reviewsNum': 24, 
    },
    {
        '_id': 8,
        'name': 'Gaza jałowa',
        'image': '/images/gaza.jpg',
        'description': 'Gaza jałowa opatrunkowa 0,25m2 17-nitkowa wykonana z 100% bawełny.',
        'price': 0.99, 
        'countInStock': 4,
        'rating': 4.5,
        'reviewsNum': 51, 
    },
    {
        '_id': 9,
        'name': 'Plaster w rolce Omnifilm 2,5cm',
        'image': '/images/plastry.jpg',
        'description': 'Hipoalergiczne przylepce foliowe Omnifilm w 2,5 cm w rolce 5 m. Do podtrzymania opatrunków wszelkiego rodzaju, do mocowań kaniul, sond, cewników itp.',
        'price': 14.50, 
        'countInStock': 4,
        'rating': 4,
        'reviewsNum': 89, 
    },
    {
        '_id': 10,
        'name': 'Bandaze 4cm*4',
        'image': '/images/band.jpg',
        'description': 'Bandaże 4cm w rolce 4m. Do podtrzymywania wszelkiego rodzaju opatrunków, szczególnie na stawach, stożkowatych i zaokrąglonych częściach ciała. Opakowanie zawiera 20 sztuk.',
        'price': 19.99, 
        'countInStock': 4,
        'rating': 4.5,
        'reviewsNum': 33, 
    },
    {
        '_id': 11,
        'name': 'Igły 0,7*30mm',
        'image': '/images/igla.jpg',
        'description': 'Igły iniekcyjne jednorazowego użytku. Rozmiar 0.70 x 30mm 22G. Wykonane z wysokiej jakości stali. Znajdują zastosowanie w iniekcji dożylnej, domięśniowej, transfuzji krwi lub pobrania krwi. Wyposażone w zatyczkę typu luer lock. Opakowanie 100 sztuk.',
        'price': 6.99, 
        'countInStock': 4,
        'rating': 4.5,
        'reviewsNum': 69, 
    },
    {
        '_id': 12,
        'name': 'Płyn do dezynfekcji',
        'image': '/images/dezynfekcja.jpg',
        'description': 'Płyn alkoholowy przeznaczony do higienicznej i chirurgicznej dezynfekcji rąk. Wykazuje działanie bakteriobójcze, bójcze wobec prątków gruźlicy, drożdżakobójcze i ograniczone wirusobójcze. Przebadany dermatologicznie. Pojemność 5 litrów.',
        'price': 119.99, 
        'countInStock': 4,
        'rating': 4.5,
        'reviewsNum': 102, 
    },
]
