# Generated by Django 4.2 on 2023-06-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_order_user_alter_product_addedtime_review_order_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
